language: java

jdk:
 - openjdk6

before_install: 
 - sudo apt-get update -qq
 - sudo apt-get install -y ant
 - sudo apt-get install -y ecj
 - env


 
install:
 - ant test

notifications:
  email:
    recipients:
        - carla.carrubba@ct.infn.it
